### ISSUE TITLE
Is there a jenkins plugin for this tool ?

### ISSUE THREAD

**Issue by ijerry** [ajinabraham/nodejsscan#142]
Hi All,

Is there a Jenkins Plugin for this tool ?

Many Thanks.

**Comment by ajinabraham** [comment]
We don't have one.

**Comment by sulaxchane** [comment]
> Hi All,
> 
> Is there a Jenkins Plugin for this tool ?
> 
> Many Thanks.

i used the docker image to run and output the results
then publish it

**Comment by prabhu** [comment]
Thank you for this wonderful project. I have integrated this with my oss [sast-scan](https://github.com/AppThreat/sast-scan) project. As an added bonus, my tool would automatically convert the report into a SARIF format so that it can be viewed with a number of viewers such as 

-  Online viewer - http://sarifviewer.azurewebsites.net/
- VS Code extension - https://marketplace.visualstudio.com/items?itemName=MS-SarifVSCode.sarif-viewer
- Visual Studio extension - https://marketplace.visualstudio.com/items?itemName=WDGIS.MicrosoftSarifViewer
- Azure DevOps extension - https://marketplace.visualstudio.com/items?itemName=sariftools.sarif-viewer-build-tab

Unfortunately, a viewer for jenkins doesn't exist yet :(

Since I started sast-scan with python it's a bit involved to convert the logic to javascript and contribute the convertor back here. However, it should be possible to use the [typescript sdk](https://github.com/AppThreat/sarif-sdk-typescript) and reimplement the convertor if someone is interested.

**Comment by ajinabraham** [comment]
This can be tracked as an enhancement, but won't happen anytime soon.

**Comment by ajinabraham** [comment]
Take a look at our new CLI tool: https://github.com/ajinabraham/njsscan
Make use of cli options for jenkins integration.
