### ISSUE TITLE
Probably needs to be rewritten to use AST

### ISSUE THREAD

**Issue by prabhu** [ajinabraham/nodejsscan#147]
After spending a bit of time testing this library with some sample dataset such as [this one](https://github.com/AppThreat/insecure-sample-projects/tree/master/javascript), I have come to the unfortunate conclusion that using just regex embedded in a xml is a serious limitation for this tool.

I think we should get inspiration from tools such as bandit and gosec: 

- They cleverly [use](https://github.com/PyCQA/bandit/blob/master/bandit/core/node_visitor.py#L7) [AST](https://github.com/securego/gosec/blob/9cb83e10afadf65448ff03018deb1862f8299986/analyzer.go#L20) to parse source code into a machine-readable format
- Rules are expressed as code so that there could be advanced logic for any lookups and filtering

I am not sure what the current state of [AST](https://github.com/Mithgol/node-abstract-syntax-tree) is for JavaScript and Node.js. Till the time we have a solid ast library we may have to stick with just regex or un-friendly services such as lgtm :(

**Comment by ajinabraham** [comment]
I agree AST is the right way to go with SAST tools. I will track this as an enhancement and see if I can do something about it.

**Comment by prabhu** [comment]
After filing this ticket I have written a blog post on this topic - https://appthreat.io/how-to-build-a-sast-tool/

Please feel free to use this article as a source for your requirements.

Thank you in advance!

**Comment by kingsleytorlowei** [comment]
Hey Ajin,
Would you mind if I look into this issue? I want to contribute and some resources would be helpful.

**Comment by ajinabraham** [comment]
@kingsleytorlowei Feel free to work on it. The tool currently is a regex/string match based SAST. For better results and to reduce false positives, AST is the way to go.

Here are some JS parsers for python,

https://github.com/Kronuz/esprima-python
https://github.com/PiotrDabkowski/pyjsparser

Instead of regex like these: https://github.com/ajinabraham/NodeJsScan/blob/master/core/rules.xml

We should be able to locate occurrence of signatures/patterns in parsed syntax tree like in the positions of imports, variables, keywords etc.

If you need any help, feel free to reach out.

**Comment by kingsleytorlowei** [comment]
Hey, @ajinabraham I've done some reading and codifying the rules is the way to go. Codifying the rules would take some work but it should be the future we're looking forward to because it offers the chance for us to be able to provide more context on the issues with uploaded code. 
What do you think?

**Comment by ajinabraham** [comment]
@kingsleytorlowei I have a different take on that. Except for very few special cases, you could write code that can be reused to support multiple rules.

For example to identify an RCE or SQLi in Node.js web app

The process is similar,  look in the AST for imports, get all user controlled variables and see if they end up in possible insecure functions which results in injection vulnerabilities. 

These two vulnerabilities can be converted into a formatted rules.
Same code can run multiple rules against the user source code.
People can easily contribute to the rules than trying to understand how the codified rule works.

**Comment by ajinabraham** [comment]
Currently rewriting nodejsscan with sgrep https://github.com/returntocorp/sgrep

**Comment by prabhu** [comment]
how is this coming along?

**Comment by ajinabraham** [comment]
We are making good progress here: https://github.com/ajinabraham/njsscan
https://github.com/ajinabraham/libsast
Waiting for semgrep to push a python binding to PyPI

**Comment by ajinabraham** [comment]
We use semantic grep now.

Take a look at our new CLI tool: https://github.com/ajinabraham/njsscan
