### ISSUE TITLE
Do you have a list of things you look for in the code?

### ISSUE THREAD

**Issue by ali-habibzadeh** [ajinabraham/nodejsscan#202]
I added

const token = crypto_1.default.createCipheriv("AES-128-ECB", "key", ""); bad idea to not provide initialization vector
const foo = eval(`console.log(a)`); bad idea to to use eval

Both of these passed the test. Am I missing something?

**Comment by ajinabraham** [comment]
I will try adding `const token = crypto_1.default.createCipheriv("AES-128-ECB", "key", ""); bad idea to not provide initialization vector`

We don't catch all `eval()` because it's very nosiy. A lot of libraries and third-party code use it internally. We catch eval only if user input is passed to eval()

**Comment by ajinabraham** [comment]
tracking this separately at njsscan

**Comment by ajinabraham** [comment]
Now added in latest master
