### ISSUE TITLE
Not written in Node

### ISSUE THREAD

**Issue by keithws** [ajinabraham/nodejsscan#210]
Based on the name, I expected this tool to be written in node JavaScript and installable via npm.

It is not. It requires Python and PostgreSQL. Furthermore, the recommended installation requires docker.

I was looking for a tool to drop into my npm run-scripts to do static analysis during npm test.

**Comment by ajinabraham** [comment]
nodejsscan is a standalone SAST management system. For your use case, what you need is the cli module named njsscan. 

Take a look at https://github.com/ajinabraham/njsscan

It is still written in python since the core AST matcher that we use is available as a python library.

You could add something like this in your npm scripts

```
pip install njsscan
njsscan <source_code_location>
```

We also have a GitHub action if you use GitHub for CI: https://github.com/marketplace/actions/nodejsscan
